//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Atdl4net.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class InternalErrors {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal InternalErrors() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Atdl4net.Resources.InternalErrors", typeof(InternalErrors).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The container method specified, &apos;{0}&apos;, was not found on the object of type {1}..
        /// </summary>
        internal static string ContainerMethodNotFoundOnObject {
            get {
                return ResourceManager.GetString("ContainerMethodNotFoundOnObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only one level of property indirection is allowed - {0} is invalid (Value.SubValue is allowed, Value.SubValue.SubSubValue is not)..
        /// </summary>
        internal static string InvalidPropertyIndirection {
            get {
                return ResourceManager.GetString("InvalidPropertyIndirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extension method String.ParseAsEnum&lt;T&gt;() can only be used with enum types..
        /// </summary>
        internal static string InvalidUseOfParseAsEnum {
            get {
                return ResourceManager.GetString("InvalidUseOfParseAsEnum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No constructor was found for the type {0} that matched the arguments supplied..
        /// </summary>
        internal static string NoConstructorFoundForSpecifiedArgumentTypes {
            get {
                return ResourceManager.GetString("NoConstructorFoundForSpecifiedArgumentTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The property {0} was not found on the target object of type {1}..
        /// </summary>
        internal static string PropertyNotFoundOnObjectInternal {
            get {
                return ResourceManager.GetString("PropertyNotFoundOnObjectInternal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It was not possible to retrieve the value of property {0} from the target object of type {1}..
        /// </summary>
        internal static string UnableToRetrievePropertyValueOnObject {
            get {
                return ResourceManager.GetString("UnableToRetrievePropertyValueOnObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It was not possible to set the value of property {0} to the value &apos;{1}&apos; on the target object of type {2}..
        /// </summary>
        internal static string UnableToSetPropertyValueOnObject {
            get {
                return ResourceManager.GetString("UnableToSetPropertyValueOnObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected type {0} used in method that expects one of {1}..
        /// </summary>
        internal static string UnexpectedArgumentType {
            get {
                return ResourceManager.GetString("UnexpectedArgumentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value supplied {0} as an argument to this method was not expected and is not supported..
        /// </summary>
        internal static string UnexpectedArgumentValue {
            get {
                return ResourceManager.GetString("UnexpectedArgumentValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field or property {0} of type {1} unexpectedly contained a null reference..
        /// </summary>
        internal static string UnexpectedNullReference {
            get {
                return ResourceManager.GetString("UnexpectedNullReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The attribute type specified, &apos;{0}&apos;, is not a supported attribute type..
        /// </summary>
        internal static string UnrecognisedAttributeType {
            get {
                return ResourceManager.GetString("UnrecognisedAttributeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The conversion from {0} value to type {1} is not supported..
        /// </summary>
        internal static string UnsupportedTypeConversion {
            get {
                return ResourceManager.GetString("UnsupportedTypeConversion", resourceCulture);
            }
        }
    }
}
